#!/bin/bash
rm -rf /var/lib/softhsm/tokens/
mkdir -p /var/lib/softhsm/tokens/
softhsm2-util --init-token --slot 0 --label "token" --so-pin 0000 --pin 0000
softhsm2-util --import testserver/key.p8 --token token --label d34db33f --pin 0000 --id d34db33f
